# Generated by Django 3.2.4 on 2023-02-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='postal_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='street_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='street_number',
            field=models.CharField(default=0, max_length=5),
        ),
    ]
