# Generated by Django 3.2.4 on 2023-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbor', '0002_auto_20230201_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='neighbor',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
